#!/usr/bin/env sh
###############################
#      FANCY BASH PROMPT      #
###############################

##  ARRANGE $PWD & STORE IT IN $NEW_PWD
bash_prompt_command() {
    local pwdmaxlen=25                                                ##  CHARACTER LIMIT FOR $PWD
    local trunc_symbol=".."                                           ##  INDICATE TRUNCATION DONE
    local dir=${PWD##*/}                                              ##  STORE LOCAL DIR
    pwdmaxlen=$(( ( pwdmaxlen < ${#dir} ) ? ${#dir} : pwdmaxlen ))    ##  SET $PWD LENGTH

    NEW_PWD=${PWD/#$HOME/\~}
 
    local pwdoffset=$(( ${#NEW_PWD} - pwdmaxlen ))

##  GENERATE NAME
    if [ ${pwdoffset} -gt "0" ]; then
        NEW_PWD=${NEW_PWD:$pwdoffset:$pwdmaxlen}
        NEW_PWD=${trunc_symbol}/${NEW_PWD#*/}
    fi
}

##  COLORIZE
bash_prompt() {
    case $TERM in
        xterm*|rxvt*)
            local TITLEBAR='\[\033]0;\u:${NEW_PWD}\007\]'
            ;;
        *)
            local TITLEBAR=""
            ;;
    esac

###  NO COLOR
local NC="\[\033[0m\]"
 
###  REGULAR COLORS
local B="\[\033[0;30m\]"
local R="\[\033[0;31m\]"
local G="\[\033[0;32m\]"
local Y="\[\033[0;33m\]"
local L="\[\033[0;34m\]"
local M="\[\033[0;35m\]"
local C="\[\033[0;36m\]"
local W="\[\033[0;37m\]"
 
###  BOLD COLORS
local EMK="\[\033[1;30m\]"
local EMR="\[\033[1;31m\]"
local EMG="\[\033[1;32m\]"
local EMY="\[\033[1;33m\]"
local EMB="\[\033[1;34m\]"
local EMM="\[\033[1;35m\]"
local EMC="\[\033[1;36m\]"
local EMW="\[\033[1;37m\]"
local EMO="\[\033[38;5;208m\]"     ##  ORANGE BOLD
local EMT="\[\033[38;5;118m\]"     ##  TOXIC GREEN
 
###  BACKGROUND COLORS
local BGK="\[\033[40m\]"
local BGR="\[\033[41m\]"
local BGG="\[\033[42m\]"
local BGY="\[\033[43m\]"
local BGB="\[\033[44m\]"
local BGM="\[\033[45m\]"
local BGC="\[\033[46m\]"
local BGW="\[\033[47m\]"
 
### USER'S COLOR
local UC=$EMW

### ROOT'S COLOR
[ $UID -eq "0" ] && UC=$R
 
PS1="$TITLEBAR ${EMK}[${UC}\u${EMK}@${UC}\h ${EMC}\${NEW_PWD}${EMK}]${EMC}\\$ ${EMT}"
##  PS1="[\u@\h \${NEW_PWD}]\\$ "

none="$(tput sgr0)"
trap 'echo -ne "${none}"' DEBUG
}

## TRUNCATE PWD & STORE IN NEW_PWD
PROMPT_COMMAND=bash_prompt_command

bash_prompt
unset bash_prompt

## EOF
